// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEMLZhBAOWwv5m6Tf5zCzogUs8Tobt6sA',
    appId: '1:469438333906:web:7079499ae60552bfa33e0b',
    messagingSenderId: '469438333906',
    projectId: 'groupmeetting',
    authDomain: 'groupmeetting.firebaseapp.com',
    storageBucket: 'groupmeetting.firebasestorage.app',
    measurementId: 'G-J4QMB0BLB8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDL1To-u1XyXrHYG0MxZxSVPO5DEdSJ79s',
    appId: '1:469438333906:android:d3ee27c2099a5839a33e0b',
    messagingSenderId: '469438333906',
    projectId: 'groupmeetting',
    storageBucket: 'groupmeetting.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZDZj0eAULV2ZC46Q3ZQzCGX7G0AarLSw',
    appId: '1:469438333906:ios:ae91d4f1e5eec1e3a33e0b',
    messagingSenderId: '469438333906',
    projectId: 'groupmeetting',
    storageBucket: 'groupmeetting.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZDZj0eAULV2ZC46Q3ZQzCGX7G0AarLSw',
    appId: '1:469438333906:ios:ae91d4f1e5eec1e3a33e0b',
    messagingSenderId: '469438333906',
    projectId: 'groupmeetting',
    storageBucket: 'groupmeetting.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEMLZhBAOWwv5m6Tf5zCzogUs8Tobt6sA',
    appId: '1:469438333906:web:1e656fc16fd60a90a33e0b',
    messagingSenderId: '469438333906',
    projectId: 'groupmeetting',
    authDomain: 'groupmeetting.firebaseapp.com',
    storageBucket: 'groupmeetting.firebasestorage.app',
    measurementId: 'G-8WL21S4C15',
  );
}
